version: '3.8'

services:
  db:
    container_name: besuscope-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: besuscope
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: besuscope-redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  api:
    container_name: besuscope-api
    build:
      context: . # Projeto está na raiz
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: 'postgres://admin:admin@db:5432/besuscope'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    command: sh -c "npm run build && npm run test && npm run start"

volumes:
  postgres_data:
